services:
  backend:
    build: ./server
    ports:
      - "4000:4000" 
    networks:
      - mern_network
    env_file: ./server/.env

  frontend:
    build: ./client
    ports:
      - "5173:5173"  
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge 

